### ISSUE TITLE
Proje çalışmıyor

### ISSUE THREAD

**Issue by Ahmetfurkandur** [yazilimdehasi/TopluResimIndirici#1]
URL'i yazıp enter a bastığım zaman ana dizinde "imgs" diye klasör oluşturuyor fakat o klasörün içine linkteki fotoğrafı indirmiyor. python bilmediğim için malesef düzeltemedim.

**Comment by Ahmetfurkandur** [comment]
ben de becerememiş olabilirim

**Comment by yazilimdehasi** [comment]
Kütüphaneleri indirdin mi? 
Hangi url ile denediğini yazabilir misin?
Bir de hata atıyor ise ekran görüntüsünü gönderebilir misin ?

**Comment by Ahmetfurkandur** [comment]
kütüphanelerin hepsini indirdim.
https://www.shutterstock.com/tr/image-photo/copy-spase-lady-boy-hugging-hampi-1394683973 linki ile denedim. 
hata fırlatmıyor bug var sanırım.

**Comment by yazilimdehasi** [comment]
Öncelikle sorunu bildirdiğin için teşekkür ederim.

Shutterstock gelen isteklerin browserdan gelip gelmediğini kontrol ediyormuş. Dolayısıyla kodda yollanan isteği reddettiği için resimler indirilemiyormuş. Kodun içerisine bir adet user-agent ekleyip isteğe header olarak verdiğimde shutterstock kontrolünü by-pass edebilmiş oldum.

Şu anda attığın linkte denediğimde fotoğrafları indirebildim, sorun çözüldü.

Hangi kısımları neden eklediğimi anlatmak için kodun içerisine yorum satırlarını ekledim.

Tekrardan teşekkürler katkı için 🙌
